name: gotruhub

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Create .env file
        run: |
          touch .env
          echo MONGO_URL = ${{ secrets.MONGO_URL }} >> .env
          echo PORT = ${{ secrets.PORT }} >> .env
          echo TOKEN_KEY = ${{ secrets.TOKEN_KEY }} >> .env
          echo username = ${{ secrets.username }} >> .env
          echo pass = ${{ secrets.pass }} >> .env
          echo CLOUD_NAME = ${{ secrets.CLOUD_NAME }} >> .env
          echo API_KEY = ${{ secrets.API_KEY }} >> .env
          echo API_SECRET = ${{ secrets.API_SECRET }} >> .env
          echo AWS_ACCESS_KEY_ID = ${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
          echo AWS_SECRET_ACCESS_KEY = ${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .env
          echo AWS_DEFAULT_REGION = ${{ secrets.AWS_DEFAULT_REGION }} >> .env
          echo AWS_REGION = ${{ secrets.AWS_REGION }} >> .env
          echo AWS_BUCKET = ${{ secrets.AWS_BUCKET }} >> .env
          echo TOKEN_SECRET = ${{ secrets.TOKEN_SECRET }} >> .env
          echo ADMIN_TOKEN_SECRET = ${{ secrets.ADMIN_TOKEN_SECRET }} >> .env
          echo AGENT_TOKEN_SECRET = ${{ secrets.AGENT_TOKEN_SECRET }} >> .env
          echo REFRESH_TOKEN_SECRET = ${{ secrets.REFRESH_TOKEN_SECRET }} >> .env
          echo PROJ_ENV = ${{ secrets.PROJ_ENV }} >> .env
          echo NODE_ENV = ${{ secrets.NODE_ENV }} >> .env

    - name: install dependicies
        run: npm install     
    - name: Build
        run: npm run build 


    # - run: npm test
    # - run: pm2 restart app-name